apps/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = "dpto_app"
urlpatterns = [
    path('new/', views.NewDepartamentoView.as_view(), name='newdpto'),
    path('list/', views.DepartamentoListView.as_view(), name='listdpto')
]

apps/empleado/urls.py
from django.urls import path
from . import views

app_name = "empleado_app"

urlpatterns = [
    path('',views.InicioView.as_view(),name='inicio'),
    path('listar_empleados/',views.EmpleadoListView.as_view(),name='empleados_all'),
    path('listar_area_emple/<departamento>/',views.AreaEmpleadoListView.as_view(),name='empleados_area'),
    path('listar_jobs/<jobs>/',views.EmpleadoxJobsListView.as_view()),
    path('listar_admin/',views.EmpleadoAdministracionListView.as_view(),name='admin'),
    path('buscar_empleado/',views.EmpleadosByKwordListView.as_view()),
    path('buscar_empleado_x_habilidades/<id>/',views.HabilidadesEmpleadosListView.as_view()),
    path('ver_empleado/<pk>/',views.EmpleadoDetailView.as_view(),name='empleado_detail'),
    path('crear_empleado/',views.EmpleadoCreateView.as_view(),name='add'),
    path('success/',views.SuccessTemplateView.as_view(), name='success'),
    path('update_empleado/<pk>/',views.EmpleadoUpdateView.as_view(), name='update'),
    path('delete_empleado/<pk>/',views.EmpleadoDeleteView.as_view(), name='delete')
]

nomina/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('hm/', include('apps.home.urls')),
    path('nomina/', include('apps.empleado.urls')),
    path('dpto/', include('apps.departamento.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<header>
    <div class="top-bar">
        <div class="top-bar-left">
            <ul class="dropdown menu" data-dropdown-menu>
                <li>
                    <a href="{% url 'empleado_app:inicio' %}">HOME</a>
                </li>
                <li>
                    <a href="{% url 'empleado_app:empleados_all' %}">List of employes</a>
                </li>
                <li><a href="{% url 'dpto_app:listdpto' %}">Departament</a></li>
                <li><a href="{% url 'dpto_app:newdpto' %}">New departament</a></li>
                <li><a href="{% url  'empleado_app:admin' %}">Admin</a></li>
            </ul>
        </div>
        <div class="top-bar-right">
            <ul class="menu">
                <li><input type="search" placeholder="Search employe"></li>
                <li><a type="button" href="{% url  'empleado_app:add' %}" class="button">Register</a></li>
            </ul>
        </div>
    </div>
</header>