apps/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = "dpto_app"
urlpatterns = [
    path('new/', views.NewDepartamentoView.as_view(), name='newdpto'),
    path('list/', views.DepartamentoListView.as_view(), name='listdpto')
]

apps/empleado/urls.py
from django.urls import path
from . import views

app_name = "empleado_app"

urlpatterns = [
    path('',views.InicioView.as_view(),name='inicio'),
    path('listar_empleados/',views.EmpleadoListView.as_view(),name='empleados_all'),
    path('listar_area_emple/<departamento>/',views.AreaEmpleadoListView.as_view(),name='empleados_area'),
    path('listar_jobs/<jobs>/',views.EmpleadoxJobsListView.as_view()),
    path('listar_admin/',views.EmpleadoAdministracionListView.as_view(),name='admin'),
    path('buscar_empleado/',views.EmpleadosByKwordListView.as_view()),
    path('buscar_empleado_x_habilidades/<id>/',views.HabilidadesEmpleadosListView.as_view()),
    path('ver_empleado/<pk>/',views.EmpleadoDetailView.as_view(),name='empleado_detail'),
    path('crear_empleado/',views.EmpleadoCreateView.as_view(),name='add'),
    path('success/',views.SuccessTemplateView.as_view(), name='success'),
    path('update_empleado/<pk>/',views.EmpleadoUpdateView.as_view(), name='update'),
    path('delete_empleado/<pk>/',views.EmpleadoDeleteView.as_view(), name='delete')
]

nomina/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('hm/', include('apps.home.urls')),
    path('nomina/', include('apps.empleado.urls')),
    path('dpto/', include('apps.departamento.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    """Model definition for Departamento."""
    name = models.CharField('Nombre', max_length=50,unique=True)
    nick = models.CharField('Apodo', max_length=20,blank=True)
    estatus = models.BooleanField('Estatus',default=False,auto_created=True,editable=False)
    
    class Meta:
        """Meta definition for Departamento."""

        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

    def __str__(self):
        """Unicode representation of Departamento."""
        return self.name

apps/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    """Form definition for ."""
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=50)

apps/departamento/views.py
from django.views.generic import ListView
from django.views.generic.edit import FormView
from apps.empleado.models import Empleado
from apps.departamento.models import *
from .forms import *
# Create your views here.

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('aqui estoy en el formulario')
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            nick = form.cleaned_data['shortname']

        )
        depa.save()
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            jobs = '3',
            departamento = depa

        )
        return super(NewDepartamentoView,self).form_valid(form)


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = "departamentos"
    def get_queryset(self):
        kword = self.request.GET.get('kword','')
        lista = Departamento.objects.filter(nick__icontains=kword)
        return lista

templates/departamento/lista.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
lista de departamentos
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            lista de departamentos
        </h1>

        <form class="cell grid-x grid-margin-x" method="get">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" placeholder="buscar departamentos" id="kword" name="kword">
            </div>
            <div class="cell large-1">
                <button class="submit success button" type="submit">buscar</button>
            </div>
        </form>

        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">Nombre</th>
                        <th width="150">Corto</th>
                        <th width="100">Estatus</th>
                        <th width="100">Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for dpto in departamentos %}
                    <tr>
                        <td>{{dpto.name}}</td>
                        <td>{{dpto.nick}}</td>
                        <td>{{dpto.estatus}}</td>
                        <td>
                            <a class="hollow button success" href="{% url 'empleado_app:empleados_area' dpto.name %}">ver Empleados</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
register departamento
{% endblock titulo %}



{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h3 class="cell">new departamento</h3>
    <div class="grid-x grid-margin-x">
        <form class="grid-x callout secondary grid-padding-x" method="post">{% csrf_token %}
            <h5 class="cell">Lider de departamento</h5>
            <div class="medium-6 cell">
                <label> first_name: 
                    {{form.nombre}}        
                </label>
            </div>
            <div class="medium-6 cell">
                <label>last_name:
                    {{form.apellido}}        
                </label>
            </div>
            <h5 class="cell">datos del departamento</h5>
            <div class="medium-6 cell">
                <label>departamento:
                    {{form.departamento}}        
                </label>
            </div>
            <div class="medium-6 cell">
                <label>nick:
                    {{form.shortname}}
                </label>
            </div>
            <button type="submit" class="medium-12 cell success button">save</button>

        </form>
    </div>
</div>



{% endblock content %}