apps/empleado/urls.py
from django.urls import path
from . import views

app_name = "empleado_app"

urlpatterns = [
    path('',views.InicioView.as_view(),name='inicio'),
    path('listar_empleados/',views.EmpleadoListView.as_view(),name='empleados_all'),
    path('listar_area_emple/<departamento>/',views.AreaEmpleadoListView.as_view(),name='empleados_area'),
    path('listar_jobs/<jobs>/',views.EmpleadoxJobsListView.as_view()),
    path('listar_admin/',views.EmpleadoAdministracionListView.as_view(),name='admin'),
    path('buscar_empleado/',views.EmpleadosByKwordListView.as_view()),
    path('buscar_empleado_x_habilidades/<id>/',views.HabilidadesEmpleadosListView.as_view()),
    path('ver_empleado/<pk>/',views.EmpleadoDetailView.as_view(),name='empleado_detail'),
    path('crear_empleado/',views.EmpleadoCreateView.as_view(),name='add'),
    path('success/',views.SuccessTemplateView.as_view(), name='success'),
    path('update_empleado/<pk>/',views.EmpleadoUpdateView.as_view(), name='update'),
    path('delete_empleado/<pk>/',views.EmpleadoDeleteView.as_view(), name='delete')
]

nomina/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('hm/', include('apps.home.urls')),
    path('nomina/', include('apps.empleado.urls')),
    path('dpto/', include('apps.departamento.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/empleado/models.py
from django.db import models
from apps.departamento.models import *
from ckeditor.fields import RichTextField
# Create your models here.
class Habilidad(models.Model):
    """Model definition for Habilidades."""
    name = models.CharField('habilidad', max_length=15)
    class Meta:
        """Meta definition for Habilidades."""

        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'
    def __str__(self):
        """Unicode representation of Habilidades."""
        return self.name + str(self.id)
class Empleado(models.Model):
    """Model definition for Empleado."""
    JOB_CHOICES =(
        ('0','ingeniero informatico'),
        ('1','ingeniero sistemas'),
        ('2','electronico'),
        ('3','administrador'),
        ('4','contador'),
        ('5','asistente'),
    )
    first_name = models.CharField('nombres', max_length=60)
    last_name = models.CharField('apellidos', max_length=60)
    full_name = models.CharField('nombre completo', max_length=120, blank=True)
    jobs = models.CharField('trabajo', max_length=1,choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', height_field=None, width_field=None, max_length=None,null=True,blank=True)
    habilidades = models.ManyToManyField(Habilidad)
    historia = RichTextField()
    class Meta:
        """Meta definition for Empleado."""
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['jobs']
        unique_together = ('first_name','last_name','jobs')
    def __str__(self):
        """Unicode representation of Empleado."""
        return self.first_name + " " + self.last_name 

apps/empleado/forms.py
from django import forms

from .models import *

class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""

        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'jobs',
            'departamento',
            'avatar',
            'habilidades',
            'historia',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple(

            )
        }

apps/empleado/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView,CreateView,TemplateView,UpdateView,DeleteView
from django.urls import reverse_lazy
# Create your views here.
from .models import Empleado
from .forms import *

class EmpleadoListView(ListView):
#    model = Empleado
    template_name = "empleado/list_all.html"
    context_object_name = "empleados"
    paginate_by = 5
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword",'')
        lista = Empleado.objects.filter(first_name__icontains=palabra_clave).order_by('-id')
        return lista

class EmpleadoAdministracionListView(ListView):
    model = Empleado
    template_name = "empleado/admin_empleados.html"
    context_object_name = "empleados"
    paginate_by = 5
    ordering = '-id'


class AreaEmpleadoListView(ListView):
    #model = Empleado
    template_name = 'empleado/area_emple.html'
    context_object_name = 'areaxemple'
    paginate_by = 5
    def get_queryset(self):
        depto = self.kwargs['departamento']        
        lista = Empleado.objects.filter(departamento__name=depto)
        return lista

class EmpleadoxJobsListView(ListView):
    #model = Empleado
    template_name = 'empleado/jobs_emple.html'
    

    def get_queryset(self):
        pjobs = self.kwargs['jobs']        
        lista = Empleado.objects.filter(jobs=pjobs)
        return lista


class EmpleadosByKwordListView(ListView):
    model = Empleado
    template_name = "empleado/by_kword.html"
    context_object_name = "empleados"
    def get_queryset(self):
        print('=====================')
        palabra_clave = self.request.GET.get("kword",'')
        lista = Empleado.objects.filter(first_name=palabra_clave)
        return lista


class HabilidadesEmpleadosListView(ListView):
    model = Empleado
    template_name = "empleado/habilidades.html"
    context_object_name = "habilidades"
    def get_queryset(self):
        pclave = self.kwargs['id']
        empleado = Empleado.objects.get(id=pclave)
        return empleado.habilidades.all()

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "empleado/detail_empleado.html"
    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo']='Empleado del mes'
        return context


class SuccessTemplateView(TemplateView):
    template_name = "empleado/success.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "empleado/create.html"
    #fields = ("__all__")
    form_class = EmpleadoForm
    success_url = reverse_lazy("empleado_app:inicio")
    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView,self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "empleado/empleado_update.html"
    fields = [
        'first_name',
        'last_name',
        'jobs',
        'departamento',
        'avatar',
        'habilidades',
        'historia',
    ]
    success_url = reverse_lazy("empleado_app:admin")
    def form_valid(self, form):
        return super().form_valid(form)
    def post(self, request, *args, **kwargs):
        return super(EmpleadoUpdateView,self).post(request, *args, **kwargs)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "empleado/delete.html"
    success_url = reverse_lazy("empleado_app:admin")


class InicioView(TemplateView):
    template_name = "inicio.html"
    

templates/empleado/admin_empleados.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
listado de empleados
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Lista de empleados de un departamento</h1>
        
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Departamento</th>
                        <th width="200">Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>
                        <td>{{empleado.id}}</td>
                        <td>{{empleado.first_name}}</td>
                        <td>{{empleado.departamento}}</td>
                        <td>
                            <a class="hollow button success " href="{% url 'empleado_app:update' empleado.id %}">editar</a>
                            <a class="hollow button alert" href="{% url 'empleado_app:delete' empleado.id %}">eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">

            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                    <li class="pagination-previous "><a href="?page={{page_obj.previous_page_number}}">atras</a></li>
                    {% endif %}


                    {% for page in paginator.page_range %}

                    {% if page == page_obj.number %}

                    <li class="current"><span class="show-for-sr">You're on page</span> {{page}}</li>
                    {% else %}
                    <li><a href="?page={{page}}" aria-label="Page">{{page}}</a></li>
                    {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next "><a href="?page={{page_obj.next_page_number}}">siguiente</a></li>
                    {% endif %}

                </ul>
            </nav>
            {% endif %}


        </div>
    </div>



</div>



{% endblock content %}

templates/empleado/area_emple.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
area por empleados
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Empleados para el departamento</h1>

        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="150">Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="50">Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ae in areaxemple %}
                    <tr>
                        <td>{{ae.first_name}}</td>
                        <td>{{ae.last_name}}</td>
                        <td>
                            <a class="hollow button success"
                                href="{% url 'empleado_app:empleado_detail' ae.id %}">ver</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">

            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                    <li class="pagination-previous "><a href="?page={{page_obj.previous_page_number}}">atras</a></li>
                    {% endif %}


                    {% for page in paginator.page_range %}

                    {% if page == page_obj.number %}

                    <li class="current"><span class="show-for-sr">You're on page</span> {{page}}</li>
                    {% else %}
                    <li><a href="?page={{page}}" aria-label="Page">{{page}}</a></li>
                    {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next "><a href="?page={{page_obj.next_page_number}}">siguiente</a></li>
                    {% endif %}

                </ul>
            </nav>
            {% endif %}


        </div>
    </div>



</div>

{% endblock content %}

templates/empleado/by_kword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>buscar empleados</title>
</head>
<body>
    <div>
        <h1>
            buscar empleados
        </h1>
        <form method="get"> {% csrf_token %}
            <input type="text" id="kword" name="kword" placeholder="ingrese nombre aquí">
            <button type="submit">buscar</button>
        </form>
    </div>
<div>
    <h3>
        resultado de la busqueda
    </h3>    
    <ul>
        
        {% for name in object_list %}
            
        <h1>
            {{name.first_name}} {{name.last_name}}
        </h1>
            {{name.historia}}
        
            
        {% endfor %}
            
    </ul>
</div>

</body>
</html>

templates/empleado/create.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
registro
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x ">
        <h3 class="cell">Registro</h3>
        <form class="grid-x grid-margin-x " method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="cell medium-6">
                <label>first_name:
                    {{form.first_name}}
                </label>
            </div>
            <div class="cell medium-6">
                <label>last_name:
                    {{form.last_name}}
                </label>
            </div>
            <div class="cell medium-3">
                <label>jobs:
                    {{form.jobs}}
                </label>
            </div>
            <div class="cell medium-3">
                <label>departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="cell medium-3">
                <label>avatar:
                    {{form.avatar}}
                </label>
            </div>
            <div class="cell large-3">
                <label>skills:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="cell large-12">
                <label>
                    <h6>
                        historia:
                    </h6>
                    {{form.historia}}
                </label>
            </div>
            <div class="cell">
                <button class="submit success button" type="submit" [disabled]="!form.form.valid">
                    Guardar
                </button>
            </div>
        </form>
    </div>
    {% endblock content %}

templates/empleado/delete.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
borrar empleado
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">

    <div class="grid-x grid-margin-x">
        <h3 class="cell">Eliminar empleado</h3>
        <form class="cell" method="post">{% csrf_token %}
            <div class="callout">
                <h5 >¿esta seguro de eliminar el empleado?</h5>
                <button class="submit alert button" type="submit">Confirmar
                </button>
            </div>
        </form>

    </div>

</div>


{% endblock content %}

templates/empleado/detail_empleado.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-margin-x center">
        <div class="card" style="width: 300px; ">
            <div class="card-divider" style="background: rgba(20, 180, 220, 0.705);">
                <p>{{empleado.first_name}} {{empleado.last_name}}</p>
            </div>

            {% if empleado.avatar %}
            <img class="thumbnail" src="{{empleado.avatar.url}}">
            {% else %}
            <img class="thumbnail" src="{% static 'img/perfilvoid.jpg' %}">
            {% endif %}

            <div class="card-section callout primary">
                <h4> {{empleado.departamento.nick}}</h4>
                <p>
                    {{empleado.historia}}
                </p>
            </div>
            <div class="card-section callout secondary">
                <p>
                    <span class="label">
                        habilidades:
                    </span>
                </p>
                <ul class="vertical menu">
                    {% for h in empleado.habilidades.all %}
                    <li>
                        {{h.name}}
                    </li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>

{% endblock content %}

templates/empleado/empleado_update.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
Modificar empleado
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x ">
        <h3 class="cell">modificar empleado</h3>
        <div class="cell">
            <form class="grid-x grid-margin-x " method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="cell medium-6">
                    <label>first_name:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label>last_name:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label>jobs:
                        {{form.jobs}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label>departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label>avatar:
                        {{form.avatar}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label>skills:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>
                        <h6>
                            historia:
                        </h6>
                        {{form.historia}}
                    </label>
                </div>
                <div class="cell">
                    <button class="submit success button" type="submit" [disabled]="!form.form.valid">
                        Guardar
                    </button>
                </div>

        </div>
    </div>

    </form>

</div>

</div>

</div>
{% endblock content %}

templates/empleado/habilidades.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document habilidades</title>
</head>

<body>
    <h1>
        habilidades
    </h1>

    <div>

        {% for h in object_list %}

        <p>
            {{h}}
        </p>

        {% endfor %}

    </div>
</body>

</html>

templates/empleado/jobs_emple.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>listado de cargos</title>
</head>
<body>
    <h1>
        Acá estan listados los cargos de los empleados
    </h1>
    

    <ul>
        
        {% for j in  object_list %}
            <li>
                {{j}}
            </li>
        {% endfor %}
            
    </ul>

</body>
</html>

templates/empleado/list_all.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
listado de empleados
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Lista de empleados</h1>
        <form class="cell grid-x grid-margin-x" method="get">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" placeholder="buscar empleado" id="kword" name="kword">
            </div>
            <div class="cell large-1">
                <button class="submit success button" type="submit">buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Departamento</th>
                        <th width="150">Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>
                        <td>{{empleado.id}}</td>
                        <td>{{empleado.first_name}}</td>
                        <td>{{empleado.departamento}}</td>
                        <td>
                            <a class="hollow button success"
                                href="{% url 'empleado_app:empleado_detail' empleado.id %}">ver</a>
                            <button class="hollow button alert" href="#">delete</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">

            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                    <li class="pagination-previous "><a href="?page={{page_obj.previous_page_number}}">atras</a></li>
                    {% endif %}


                    {% for page in paginator.page_range %}

                    {% if page == page_obj.number %}

                    <li class="current"><span class="show-for-sr">You're on page</span> {{page}}</li>
                    {% else %}
                    <li><a href="?page={{page}}" aria-label="Page">{{page}}</a></li>
                    {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next "><a href="?page={{page_obj.next_page_number}}">siguiente</a></li>
                    {% endif %}

                </ul>
            </nav>
            {% endif %}


        </div>
    </div>



</div>



{% endblock content %}

templates/empleado/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        success! 
    </h1>
</body>
</html>